// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egutvziykwsbjxhlmxfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVndXR2eml5a3dzYmp4aGxteGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NTI5NTYsImV4cCI6MjA2MTUyODk1Nn0.SlgyG4wVYXBN8VnsG_w2Ifh9MYzKdpJw8rhOwD1bJzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);